<?php
namespace ERD\SearchBundle\Search\Tests;

use ERD\SearchBundle\Search\LuceneSearch;
/**
 * Test class for LuceneSearch.
 * Generated by PHPUnit on 2012-06-23 at 19:12:51.
 */
class LuceneSearchTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var LuceneSearch
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new LuceneSearch;
    }

    /**
     * @covers ERD\SearchBundle\Search\LuceneSearch::find
     * @todo Implement testFind().
     */
    public function testFind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ERD\SearchBundle\Search\LuceneSearch::emptyIndex
     * @todo Implement testEmptyIndex().
     */
    public function testEmptyIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
